// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IpInfo = { ip: string, asn: number | null, asOrganization: string | null, country: string | null, countryCode: string | null, region: string | null, city: string | null, 
/**
 * IANA 时区名，例如 America/New_York。启动前的时区对齐就是拿它比对。
 */
timezone: string | null, 
/**
 * 0–100，越低越干净。
 */
fraudScore: number | null, isResidential: boolean | null, isBroadcast: boolean | null, };
