// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Check } from "./Check";

export type PanelVerdict = { purity: Check, residential: Check, native: Check, 
/**
 * 三项全 Pass 才是 true。任一项 Unknown 都不算通过。
 */
passed: boolean, note: string, };
