// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AssetItem = { name: string, path: string, 
/**
 * 字节数。`#[ts(type = "number")]`：ts-rs 默认把 u64 映射成 bigint，
 * 而 JSON 上它就是个普通数字。文件大小要到 9 PB 才碰得到 2^53。
 */
size: number, modified: string | null, is_dir: boolean, };
