// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackupEntry = { id: string, path: string, created: string, 
/**
 * 字节数。同 `AssetItem::size`：JSON 上是普通数字，不是 bigint。
 */
size: number, };
