// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeCall } from "./BridgeCall";

export type BridgeTelemetry = { records: Array<BridgeCall>, total: number, offset: number, has_more: boolean, 
/**
 * 缓存命中率 0–1。`None` = 桥没给这一项。
 */
hit_rate: number | null, cache_read: number, cache_write: number, 
/**
 * 可统计的调用数（桥自己的口径）。
 */
countable: number, 
/**
 * 前缀可复用的比例 0–1。`None` = 桥没给。
 */
prefix_reusable: number | null, };
