// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetItem } from "./AssetItem";

export type CategoryListing = { id: string, label: string, dir: string, exists: boolean, items: Array<AssetItem>, };
