// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaudeZhInstall } from "./ClaudeZhInstall";
import type { ClaudeZhProfile } from "./ClaudeZhProfile";
import type { ClaudeZhState } from "./ClaudeZhState";

export type ClaudeZhStatus = { install: ClaudeZhInstall, claude_version: string | null, app_dir: string | null, state: ClaudeZhState, 
/**
 * 一句能照着做的话。
 */
detail: string, files_present: boolean, profiles: Array<ClaudeZhProfile>, 
/**
 * 本机那份上游副本。
 */
package_tag: string | null, package_commit: string | null, 
/**
 * 最近一次查到的上游最新版。`None` = 还没查过。
 */
latest_tag: string | null, latest_checked_at: string | null, 
/**
 * 本机已有一版、而上游最新版跟它不一样（而且没被停用）。一版都没下过时是 `false`。
 */
update_available: boolean, blocked: Array<string>, applied_tag: string | null, applied_claude: string | null, applied_at: string | null, 
/**
 * Claude 桌面端开着几个进程。`None` = 查不到（**不是「没有」**）。编排层填。
 */
desktop_running: number | null, upstream: string, };
