// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一条高危规则（跟 EasyAG 的 `danger-rules.json` 同形）。
 */
export type DangerRule = { id: string, name: string, description: string, pattern: string, flags: string, enabled: boolean, };
