// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 官方插件清单状态。仓库尚未创建时明确保持停用，插件页也不会接受任意 URL。
 */
export type OfficialCatalogStatus = { configured: boolean, source: string | null, signed: boolean, detail: string, };
