// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DependencyCheck } from "./DependencyCheck";
import type { PluginState } from "./PluginState";

export type PluginStatus = { id: string, name: string, state: PluginState, detail: string, 
/**
 * 逐项依赖检查结果，界面上摊开显示，便于用户自己看缺什么。
 */
checks: Array<DependencyCheck>, };
