// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TavernEvidence } from "./TavernEvidence";

export type TavernCandidate = { path: string, evidence: TavernEvidence, 
/**
 * 一句话说明为什么排在这里（「最近改过」「路径里带『备份』」…）。
 */
note: string, score: number, };
