// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UiLogLine = { at: string, 
/**
 * `CDP` / `AUTO-ACCEPT` / `SECURITY ALERT` / `OPTION` / `SYSTEM`。
 */
category: string, message: string, };
