// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UiConfig } from "./UiConfig";
import type { UiLogLine } from "./UiLogLine";
import type { UiSource } from "./UiSource";

export type UiStatus = { running: boolean, 
/**
 * 引擎连的调试端口（合计口径：第一个有端口的源）。没跑 / 读不到就是 0。
 */
port: number, targets: number, sockets: number, 
/**
 * 两个产品各自的情况。界面按源分行显示。
 */
sources: Array<UiSource>, 
/**
 * 回读核实过的页面数（两个源合计）。
 */
verified: number, 
/**
 * 上一次**自动附加**失败的原因（起了反重力但引擎没接上）。空 = 没有失败记录。
 * 0.26.0 这句只写进审计日志，界面上一片安静 —— 使用者看到的就只有「还是英文」。
 */
last_attach_error: string, inject_count: number, approve_count: number, block_count: number, cdp_error: string, config: UiConfig, dict_entries: number, rules_total: number, rules_on: number, rules_path: string, 
/**
 * Hub 装没装（位置表 `install::antigravity`）。
 */
hub_installed: boolean, 
/**
 * IDE 装没装。
 */
ide_installed: boolean, 
/**
 * 任意一个产品的调试端口文件在不在 —— 起过（不一定还在跑）。
 */
port_file_present: boolean, log: Array<UiLogLine>, detail: string, };
