// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 中转站服务的哪个工具。
 *
 * 三个是各自独立的列表 —— 切 Codex 的供应商不该动到 Claude 那边。
 */
export type RelayTarget = "claude-desktop" | "claude-code" | "codex";
