// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowserExtension } from "./BrowserExtension";
import type { PolicyValue } from "./PolicyValue";

/**
 * Chrome 隐私面的只读审计结果。
 */
export type BrowserAudit = { chrome_installed: boolean, chrome_path: string | null, 
/**
 * `WebRtcIPHandling` 现在是什么。`None` = 没设过策略（**不等于安全**，
 * 那表示用的是 Chrome 自己的默认值）。
 */
webrtc: PolicyValue | null, 
/**
 * `DnsOverHttpsMode`。
 */
doh: PolicyValue | null, extensions: Array<BrowserExtension>, 
/**
 * **没能检查的项，以及为什么。**
 *
 * 「没查」绝不能显示成「没问题」—— 这一档跟 `chrome_scanned` 同源。
 */
unchecked: Array<string>, };
