// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一个 Codex 桌面端**实例**（Electron 主进程；渲染 / GPU 这些子进程不单列）。
 */
export type CodexDesktopProcess = { pid: number, started: string, 
/**
 * 这个实例用的 Electron 资料目录（`--user-data-dir`）。`None` = 默认那份
 * （`%APPDATA%\Codex`：开始菜单、任务栏、`codex://` 链接、别的程序起的都是它）。
 */
profile: string | null, 
/**
 * 是不是面板起的（资料目录在面板自己的目录下，见 [`is_panel_profile`]）。
 *
 * 起槽位 / 切槽位之前只关这些 —— 见 [`close_ours`]。
 */
ours: boolean, };
