// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 怎么清掉一份外部副本。
 */
export type ExternalMethod = "npm" | "winget" | "scoop" | "delete" | "registry";
