// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagedAppStatus } from "./ManagedAppStatus";

export type ManagedStatus = { root: string, default_root: string, is_default: boolean, apps: Array<ManagedAppStatus>, };
