// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalMethod } from "./ExternalMethod";
import type { ManagedApp } from "./ManagedApp";

export type ManagedExternal = { app: ManagedApp, method: ExternalMethod, 
/**
 * 要删的文件，或者要卸载的包名 / 登记项名。
 */
target: string, 
/**
 * 给人看的一句话：会做什么。
 */
action: string, };
