// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallTarget } from "./InstallTarget";

export type PackageProbe = { target: InstallTarget, id: string, found: boolean, available_version: string | null, installed_version: string | null, };
