// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 怎么处理这一项。
 */
export type PurgeAction = "delete_file" | "delete_dir" | "npm_uninstall" | "winget_uninstall" | "scoop_uninstall" | "registry_delete" | "env_unset" | "path_entry_remove" | "shell_line_remove" | "credential_delete" | "startup_remove" | "appx_remove";
