// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 要卸哪一个。
 *
 * 比 `managed::App` 多两个：桌面端（官方安装器装的，面板接管不了它的目录）
 * 与 Chrome（浏览器，只在使用者点名时才处理）。
 */
export type PurgeTarget = "claude-code" | "codex" | "claude-desktop" | "chrome";
