// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaudeInstall } from "./ClaudeInstall";
import type { Software } from "./Software";

/**
 * 「环境与安装」页要的一整份本机现状。
 *
 * # 为什么它是个结构体而不是 `serde_json::json!{}`
 *
 * 原来 `detect_software` 命令返回的是 `serde_json::Value`，前端手抄了一个
 * `SoftwareReport` 接口。那个接口**在 Rust 侧根本不存在** —— 它没有源头，
 * 所以也没有任何东西能发现它抄错了或者过期了。
 * `api.ts:63-72` 的注释里记着一次真实事故：`targets.rs` 加了新布局，
 * 前端类型没跟上，而 `npm run types:check` 看不见手写的那些。
 *
 * 现在它有源头了：这个结构体由 ts-rs 导出，两边对不上 CI 当场红。
 */
export type SoftwareReport = { claudeCode: Software, 
/**
 * 本机全部 Claude Code 副本（不含桌面端存根）。
 */
claudeCodeInstalls: Array<ClaudeInstall>, claudeDesktop: Software, codex: Software, browsers: Array<Software>, };
