// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Software = { id: string, name: string, installed: boolean, version: string | null, path: string | null, 
/**
 * 检测到但建议重装时给出的理由。
 */
advisory: string | null, };
