// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Trace = { 
/**
 * `credential` / `config` / `install` / `registry` / `browser`
 */
kind: string, label: string, path: string, detail: string, };
