// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Trace } from "./Trace";

export type TraceReport = { traces: Array<Trace>, chrome_installed: boolean, chrome_path: string | null, chrome_running: boolean, 
/**
 * Chrome 正在跑时它的资料文件被占着，扫不了。
 * **这时候要如实说「没扫」，不能报「没找到」** —— 那是两回事。
 */
chrome_scanned: boolean, winget_available: boolean, };
