// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 最新那一版的信息。**只用来显示与比较**，里面没有一个字段会被当成下载地址。
 */
export type UpdateInfo = { 
/**
 * 三段数字，例如 `0.25.4`。
 */
version: string, 
/**
 * `v` + 版本号。
 */
tag: string, 
/**
 * 发布时刻（`update.json` 里写的，RFC 3339）。没写就是 `None`。
 */
published_at: string | null, 
/**
 * 给人看的更新说明（中文那一段）。纯文本，按行排：`## ` 开头是小标题、`- ` 开头是条目。
 */
notes: string, 
/**
 * 这一版的 Release 页面，给「在 GitHub 上看」用。
 */
page_url: string, };
