// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpgradeAction = "fresh_install" | "upgrade" | "up_to_date" | "would_downgrade" | "unknown" | "version_unreadable";
