// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpgradeAction } from "./UpgradeAction";

export type UpgradePlan = { installed: string | null, available: string | null, action: UpgradeAction, detail: string, };
