// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KillTarget } from "./KillTarget";

export type KillReport = { targets: Array<KillTarget>, killed: Array<number>, failed: Array<[number, string]>, relocked: number, 
/**
 * 枚举到但**故意没动**的进程，连同放过的理由。界面上要显示出来。
 */
spared: Array<string>, };
