// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 这个进程属于哪一边。**只用于告诉用户「关掉了什么」，不参与判定。**
 *
 * 切账户的确认框按它报数：「会关掉：桌面端 13 个、Claude Code 会话 2 个、酒馆桥接 1 个」。
 * （v0.8.0 还拿它决定切完「重新打开哪个」；v0.9.0 起切完不启动任何东西。）
 */
export type KillRole = "desktop" | "code" | "bridge" | "antigravity";
