// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DesktopState } from "./DesktopState";
import type { Slot } from "./Slot";
import type { SyncReport } from "./SyncReport";

/**
 * 账户页要的一整份现状。
 *
 * # 为什么它是个结构体而不是 `serde_json::json!{}`
 *
 * 同 [`super::detect::SoftwareReport`] 的理由：临时拼出来的对象在 Rust 侧
 * 没有类型，前端手抄的那一份也就没有源头 —— 抄错了、过期了，没有任何东西
 * 会发现。而这是首页的主数据源。
 *
 * 两条 caveat 也在里面，**它们是界面上必须固定打出来的话**：
 * 「剩余天数查不出被风控下线」「套餐读的是本机文件不是接口」。
 * 放进契约里，前端就不可能漏显示（少了字段编译不过）。
 */
export type AccountsReport = { slots: Array<Slot>, 
/**
 * 剩余天数只读本地时间戳，查不出「被风控下线」。
 */
caveat: string, 
/**
 * 套餐是怎么读出来的 —— 界面上要如实说明，不能让人以为是查了接口。
 */
planCaveat: string, sync: SyncReport, desktop: DesktopState, 
/**
 * 本机有酒馆桥接的数据目录 —— 有的话切换会一起切它。
 */
bridgePresent: boolean, };
