// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一个模型此刻（IDE 上次同步时）的额度。
 */
export type AntigravityModelQuota = { 
/**
 * IDE 里显示的名字，原样。
 */
label: string, 
/**
 * 模型枚举号；生成记录里 `model_enum` 是 `MODEL_PLACEHOLDER_M<号>`。`0` = 没读到。
 */
model_id: number, 
/**
 * 剩余比例 0–1。`None` = 这一条没带额度信息。
 */
remaining: number | null, 
/**
 * 重置时刻，本地时间 `YYYY-MM-DD HH:MM`。
 */
reset_at: string | null, 
/**
 * 重置时刻的 Unix 秒，给界面算「几小时后」用。
 */
reset_epoch: number | null, 
/**
 * "Fast" / "Limited time" 之类的标签，原样。
 */
tags: Array<string>, };
