// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenBucket } from "./TokenBucket";

/**
 * 一次扫描的结果。计数不是装饰：它们是「这份统计覆盖了多少」的证据。
 */
export type AntigravityUsageScan = { buckets: Array<TokenBucket>, 
/**
 * 读成功的 `.db` 数。
 */
files_read: number, 
/**
 * 打不开 / 表不对 / 读到一半出错的 `.db` 数。
 */
files_failed: number, 
/**
 * 旧 `.pb` 归档数（没读）。
 */
legacy_skipped: number, 
/**
 * 解不出用量或时间的生成记录数。
 */
incomplete: number, 
/**
 * 同一个对话 id 在第二个目录里又出现一次（`antigravity-backup` 之类），只数第一份。
 */
duplicates: number, 
/**
 * 扫过的目录（给「统计说明」看）。
 */
scanned_dirs: Array<string>, };
