// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AntigravityModelQuota } from "./AntigravityModelQuota";

/**
 * 一个账户在界面上的样子。两半各自独立。
 */
export type AntigravityAccount = { id: string, label: string, active: boolean, 
/**
 * `--user-data-dir` 指向哪里。`None` = 这条槽位还没有 IDE 那一半。
 */
ide_dir: string | null, ide_logged_in: boolean, 
/**
 * 一句人话：已登录 / 未登录 / 状态库不可读。
 */
ide_auth_state: string, 
/**
 * IDE 那一半的登录**读不出来**（状态库打不开 / 正忙 / 目录读不了，2026-09-25）。
 *
 * 这时 `ide_logged_in` 是 false，但**不是「未登录」**（§7.17）：原来界面照样画「IDE 未登录」、
 * 摆一颗「登录」、把刷新图标灰掉 —— IDE 写库时占着锁超过 250 毫秒，15 秒一轮的读就把一个
 * 登着的账户说成没登录。
 */
ide_unreadable: boolean, 
/**
 * IDE 自己写下的邮箱与档位。读不到就是 `None`。
 */
email: string | null, tier: string | null, 
/**
 * 读账户状态时出的错。**跟「`email` 是 `None`」不是一回事**，见 [`ide::AntigravityIdeSlot`]。
 */
identity_error: string | null, 
/**
 * 各模型剩余额度（画配额条用）。没登录 / 读不出来就是空的。
 */
quota: Array<AntigravityModelQuota>, 
/**
 * IDE 那份状态库最后写入的时间，本地 `YYYY-MM-DD HH:MM`。
 *
 * ⚠ 配额只有 IDE 上次同步时那么新，界面必须写「IDE 写入 hh:mm」，不许说成此刻。
 */
written_at: string | null, 
/**
 * `GEMINI_CLI_HOME` 指向哪里。`None` = 这条槽位还没有 CLI 那一半。
 */
cli_dir: string | null, cli_logged_in: boolean, cli_auth_state: string, 
/**
 * CLI 那一半的凭据文件读不出来（不是「没有」）。同 `ide_unreadable`。
 */
cli_unreadable: boolean, };
