// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 点数余额。Codex 写什么就报什么，读不到就是 `None`。
 */
export type CodexCredits = { has_credits: boolean, unlimited: boolean, 
/**
 * 余额。`None` = 这条记录没带。
 */
balance: number | null, };
