// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodexSlot } from "./CodexSlot";

export type CodexAccounts = { slots: Array<CodexSlot>, launched_id: string | null, launched_pid: number | null, launched_at: string | null, };
