// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 某一天的请求数。
 */
export type CodexDayCount = { 
/**
 * `YYYY-MM-DD`，本地时区。
 */
day: string, requests: number, };
