// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeleteOutcome = { label: string, 
/**
 * 真的删掉了哪几个目录。界面照它报数，不照请求报数。
 */
removed: Array<string>, notes: Array<string>, };
