// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GeminiSlot = { id: string, label: string, active: boolean, logged_in: boolean, 
/**
 * 一句人话：已登录 / 未登录 / 文件不可读。
 */
auth_state: string, 
/**
 * `GEMINI_CLI_HOME` 指向的目录，给界面显示。
 */
home: string, };
