// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncReport = { 
/**
 * 这次真的做了的事。空 = 本来就是一份，什么都没动。
 */
done: Array<string>, 
/**
 * 没做成的（通常是桥接正在用那个目录），下次列槽位时会再试。
 */
failed: Array<string>, };
