// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一个「日 × 模型」桶。按本机本地时区切天 —— 使用者看的是自己的日历。
 */
export type TokenBucket = { 
/**
 * `YYYY-MM-DD`，本地时区。
 */
day: string, 
/**
 * 官方写下的模型名，原样给出，不做任何美化或归并。
 */
model: string, input: number, output: number, cache_write: number, cache_read: number, 
/**
 * 这个桶里有几条回复。
 */
messages: number, };
