// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenBucket } from "./TokenBucket";
import type { TokenEmptyDay } from "./TokenEmptyDay";
import type { TokenHourBucket } from "./TokenHourBucket";
import type { TokenRequest } from "./TokenRequest";

/**
 * 一个槽位的 token 统计。
 *
 * 后面那几个计数不是装饰，它们是「这份统计覆盖了多少」的证据。
 * 只给总数的话，「读了 41 个文件」和「读了 3 个、38 个打不开」
 * 在界面上长得一模一样。
 */
export type TokenUsage = { 
/**
 * 日 × 模型，按 `day` 再按 `model` 升序。
 */
buckets: Array<TokenBucket>, 
/**
 * 有用量记录的会话数（子代理并进父会话）。
 */
sessions: number, 
/**
 * 读成功的转写文件数。
 */
files_read: number, 
/**
 * 打不开或读坏了的转写文件数。不为零就要在界面上说。
 */
files_failed: number, 
/**
 * 被去重丢掉的条数。见文件头 —— 这个数通常和留下的一样大。
 */
duplicates: number, 
/**
 * 没有可用时刻、落不进任何一天的条数。
 */
undated: number, 
/**
 * 默认目录里**归不到任何槽位**的用量，同样按日 × 模型分桶。
 *
 * 单独一列而不是并进 `buckets`：它不属于这个账户，也不属于别的账户 ——
 * 摊给谁都是编。界面把它当成一行旁注显示。
 */
unattributed: Array<TokenBucket>, 
/**
 * 四类全 0、没有入账的回复数（报错、被打断）。见文件头。
 */
empty_replies: number, 
/**
 * 同上，按天。没有时刻的不在这里（落不进任何一天）。
 */
empty_days: Array<TokenEmptyDay>, 
/**
 * 最近 48 小时，日 × 小时 × 模型。
 */
hourly: Array<TokenHourBucket>, 
/**
 * 最近的回复，新的在前，最多 [`RECENT_CAP`] 条。
 */
recent: Array<TokenRequest>, };
