// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一块网卡。**只如实报告，不替使用者判断哪块是物理网卡、哪块是 TUN。**
 *
 * 猜错的后果是把 Block 规则加到 TUN 上（浏览器直接断网），
 * 或者漏掉真正的物理网卡（等于没拦，而界面显示已生效）。
 * 两种都比「让使用者自己选」糟得多 —— 跟 `sysenv::iana_to_windows`
 * 查不到就不猜是同一条规矩。
 */
export type NetAdapter = { name: string, 
/**
 * 驱动报上来的描述，形如 `Realtek Gaming 2.5GbE Family Controller`。
 * 使用者主要靠这一行认出哪块是虚拟网卡。
 */
description: string, up: boolean, };
