// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StepRecord } from "./StepRecord";

export type Progress = { steps: { [key in string]?: StepRecord }, 
/**
 * 引导是否已整体走完一轮。走完后侧栏序号换成状态灯。
 */
completed_once: boolean, };
