// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Settings = { 
/**
 * Codex 要不要也归 IP 门禁管。
 *
 * **默认 false，而且必须一直是 false。** 打开之后 `codex` 会跟
 * `claude.exe` 一样被加上 Deny ExecuteFile —— 出口 IP 不在白名单时
 * 命令直接被系统拒绝执行。这对「请求不能从没核实过的 IP 出去」是对的，
 * 但对一个正在用 Codex 干活的人来说是个突然的变化，
 * 所以只能由他自己在设置里打开。
 */
codex_under_gate: boolean, 
/**
 * 门禁被动关上之后，出口 IP 回到白名单时要不要自动重新放行。
 *
 * **默认 true。** 关闭后监督服务继续运行，但不会自动重新放行 ——
 * 出口 IP 后来恢复了也不会有人开门，使用者只会在下次开新会话时撞见
 * `Claude Code couldn't start`，而且完全不知道这跟半小时前那次网络抖动有关。
 *
 * 打开它**不放松任何安全性质**：重新放行仍然要求出口 IP 已核实且在白名单里，
 * 跟 `Tick::ReclaimLease` 守的是同一条不变量。而且它**只恢复租约、
 * 不启动任何进程**，也不读限流状态 —— README 合规边界那四条一条都没碰。
 */
gate_auto_rearm: boolean, 
/**
 * 面板托管安装的根目录（v0.9.0）。Claude Code 装在 `<它>\claude-code\`，
 * Codex 装在 `<它>\codex\`。
 *
 * **`None` = 默认位置** `%LOCALAPPDATA%\ClaudeIpGate\apps` —— 不把本机的绝对路径
 * 写进配置，换一台机器、换一个用户名照样对。
 *
 * ⚠ 只能经 `managed::set_dir` 改（它会先实测新目录锁不锁得住、再把已装的搬过去）。
 * `settings_save` 会忽略前端传来的这个字段 —— 不然前端改个开关顺手把它改了，
 * 文件还在旧目录，面板就又「找不到软件」了。
 */
managed_apps_dir: string | null, 
/**
 * 国家白名单（ISO 3166-1 alpha-2 大写）。
 *
 * **默认空，空 = 这一层不启用。** 不能让空名单等于全拒 ——
 * 使用者装完面板、还没来得及配国家名单时，全拒会把他直接关在门外，
 * 与硬约束 4「白名单为空时不许上锁」是同一类事故。界面上必须
 * 显著标注「国家层未启用」，别让人以为配了。
 *
 * 启用之后这一层是**硬的**：出口 IP 落在名单外、查不出国家、
 * 或者几个探测源报的国家互相打架，一律按不合格处理（见 `gate::judge`）。
 * 代价写在 DISCLAIMER 里：GeoIP 不准会误杀正在进行的会话。
 */
country_allowlist: Array<string>, 
/**
 * 会话内门禁（装进 Claude Code 的 hook）要不要开。
 *
 * **默认 false** —— 它会在门禁判不过时拦下每一次请求，是个会让
 * 「本来能用的东西突然不能用」的开关，跟 `codex_under_gate` 同一档，
 * 必须由使用者自己打开。
 *
 * 这个字段存的是**意图**，不是现状：每个槽位的 `settings.json` 里
 * 装没装才是现状。切换账户后 `usecase::hook_ops::follow_active_slot`
 * 拿它把现状对齐回来。
 */
hook_enabled: boolean, 
/**
 * 启动 Claude Code 时关掉非必要遥测（崩溃报告、使用统计）。
 *
 * **默认 false。** 两个理由：一是它会改变现有使用者升级后的行为，
 * 二是它放在 IP 锁和国家白名单旁边，极容易被读成「防封的一环」——
 * **它跟封号风险无关**，让人对一件不保护他的事感到安全，比不做更糟。
 *
 * 具体设哪几个变量见 `launch::TELEMETRY_OFF`，界面上原样列出来供核对。
 */
disable_telemetry: boolean, 
/**
 * 启动面板时，把**系统时区**对齐到出口 IP 的归属地。
 *
 * **默认 true** —— 这是使用者明确要的（「时区对齐应该是本项目的默认启动功能」）。
 * 已经一致时直接跳过，不做任何动作、也不弹 UAC；只有真的不一致才切，
 * 而切时区需要管理员权限，那一次会弹一个 UAC。
 *
 * 查不到出口 IP、或者对照表里没有那个时区时**不切也不猜**，只在日志里记一句
 * （`sysenv::iana_to_windows` 返回 `None` 就报错）。
 */
align_timezone_on_start: boolean, 
/**
 * 启动面板时，把**区域格式**（日期、数字、货币）对齐到出口 IP 的归属地。
 *
 * **默认 true**：`Set-Culture` 不需要管理员权限、不用重启，改完之后新开的
 * 程序就读到新值 —— 代价小到可以默认开。
 */
align_locale_on_start: boolean, 
/**
 * 启动面板时，把**显示语言**对齐到出口 IP 的归属地。
 *
 * **默认 false，跟上面两个不一样。** 理由是代价完全不同：它要先装好对应的
 * 语言包，而且**要注销一次才生效**。默认开的话，使用者装完面板第二天发现
 * 系统提示要注销，或者语言包没装、设了等于没设 —— 两种都属于
 * 「突然发生一件我没要求的事」，正是这个文件开头那条默认值规矩要挡的。
 *
 * 要用的人自己在设置里打开，界面上把「要语言包、要注销」写在开关旁边。
 */
align_display_language_on_start: boolean, };
