// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckItem } from "./CheckItem";
import type { EnvHit } from "./EnvHit";
import type { SecretHit } from "./SecretHit";

export type Checkup = { items: Array<CheckItem>, 
/**
 * 明文密钥的位置清单。**没有任何密钥内容。**
 */
secrets: Array<SecretHit>, 
/**
 * 相关环境变量的清单。值都掩码过，见 `mask_env_value`。
 */
env: Array<EnvHit>, };
