// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ipv6Binding } from "./Ipv6Binding";

export type Ipv6Status = { disable: boolean, busy: boolean, bindings: Array<Ipv6Binding>, restore_pending: number, error: string | null, };
