// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 当前系统代理长什么样。
 *
 * 每个可选项的 `None` 都表示**这个值不存在**，跟「存在但是空串」是两回事 ——
 * 还原时前者要把值删掉、后者要写一个空串。跟 `locale::LocaleState::original_ui`
 * 是同一条：合并这两种状态，回滚就会留下一个使用者原来没有的键。
 */
export type ProxyState = { 
/**
 * `ProxyEnable`。手动代理开没开。
 */
enabled: boolean, 
/**
 * `ProxyServer`，形如 `127.0.0.1:7890`。
 */
server: string | null, 
/**
 * `ProxyOverride`，绕过列表。
 */
bypass: string | null, 
/**
 * `AutoConfigURL`，PAC 脚本地址。
 *
 * **跟 `server` 是两条独立的路径。** 只看 `enabled` / `server` 会漏掉它：
 * 手动代理关着、PAC 却还挂着的机器，流量照样被 PAC 接管，
 * 而界面会显示「没开代理」。
 */
pac: string | null, };
