// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一处明文密钥。**只有位置，没有内容。**
 */
export type SecretHit = { file: string, 
/**
 * 字段名，比如 `api_key`。**值永远不带出来。**
 */
field: string, };
