// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuditSample = { stage: string, request_id: string, api_tokens: [number | null, number | null, number | null, number | null], ledger_tokens: [number | null, number | null, number | null, number | null], billed: number | null, official: number | null, first_token_ms: number | null, match_kind: string, problem: string | null, };
