// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditSample } from "./AuditSample";

export type AuditBatch = { planned: number, samples: Array<AuditSample>, balance_before: number | null, balance_after: number | null, balance_delta: number | null, currency: string, total_billed: number | null, official_cost: number | null, prefix_reuse: number | null, };
