// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckKind } from "./CheckKind";
import type { Verdict } from "./Verdict";

/**
 * 一项检验的结果。三个数对应报告页那三根条子。
 *
 * TS 侧叫 `AuditCheck`:`qb-probe` 那边已经有一个 `Check`(纯枚举
 * Pass/Fail/Unknown),两个类型会导出成同一个 `Check.ts`,**后写的把先写的
 * 盖掉而且不报错**。实测过一次:`AuditRound.checks` 当时被标成了
 * `Array<"Pass"|"Fail"|"Unknown">`,`npm run types:check` 照样全绿 ——
 * 它比的是「生成的和仓库里的一不一样」,而两次生成都一样地错。
 */
export type AuditCheck = { kind: CheckKind, 
/**
 * 标称：站点自己说的。
 */
claimed: number | null, 
/**
 * 上次：上一轮实测到的。首次检验时是 `None` ——
 * **第三根条子不画成 0,写「首次检验」。**
 */
previous: number | null, 
/**
 * 实测：这一轮量出来的。
 */
measured: number | null, verdict: Verdict, };
