// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheapBasis } from "./CheapBasis";
import type { Ranking } from "./Ranking";

/**
 * 排一次序。**只排,不换** —— 换上游是 [`station_select_route`] 的事,
 * 那一步要由使用者或明确的自动调度触发,不能藏在一个「看看排名」的命令里。
 */
export type DecisionView = { ranking: Ranking, 
/**
 * 「便宜」这一维用的是哪种口径。界面要照实写出来。
 */
basis: CheapBasis, };
