// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Axis } from "./Axis";

/**
 * 没过某条底线,以及差在哪。界面要把这个原样写出来。
 */
export type FloorMiss = { axis: Axis, actual: number, limit: number, };
