// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Evidence } from "./Evidence";
import type { KillRole } from "./KillRole";

export type KillTarget = { 
/**
 * 进程创建时间（Windows FILETIME）。**过 IPC 时是字符串。**
 *
 * 跟 `domain::Session::process_created` 同一个理由：这个值超过
 * JS 的安全整数上限，当数字传过去会被静默截断。而它正是
 * `sessions::terminate_verified` 用来判断「PID 是不是被复用了」的依据 ——
 * 抹掉几位之后那个判断会错，且完全没有症状。
 *
 * 手写的那份前端类型把它声明成 `number`，这个问题就一直藏着，
 * 直到 B1 把类型换成 ts-rs 生成的才露出来（生成的是 `bigint`）。
 */
process_created: string, pid: number, name: string, path: string | null, evidence: Evidence, role: KillRole, };
