// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MigrateReport = { from: string, to: string, moved: Array<string>, 
/**
 * 为了搬走正在运行的 Claude Code，先关掉了几个 Claude 进程。
 */
closed: number, };
