// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一个价格是抄来的还是推出来的。
 *
 * **必须分开。** 缓存价按标准倍数推,对绝大多数模型成立,但**有例外** ——
 * 官方对某些模型单独定过缓存读价。把推出来的当成抄来的,
 * 那几个模型的真实倍率就会系统性地算错,而界面上一切正常。
 */
export type PriceBasis = "published" | "derived";
