// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Protocols } from "./Protocols";
import type { StationModel } from "./StationModel";

/**
 * ⚡ 探测：这家站点支持哪几种协议、公布了哪些模型的价。
 *
 * **免费。** 协议那一步发的是故意不合法的空 body（上游连模型都不碰），
 * 价目那一步读的是站点自己的 `/api/pricing`。两步都不产生 token。
 *
 * # ⛔ 探不出来的留空，不猜
 *
 * 协议是三态：探通 / 上游明确拒绝 / 不知道。Key 打错时三条会一起 401，
 * 那时候正确答案是「不知道」—— 猜成「都不支持」会让这条线路在界面上
 * 整个消失，而使用者只是少粘了一位。
 *
 * 价目拉不到就如实说「这个站点没开 /api/pricing」，**不编一个倍率**。
 */
export type ProbeResult = { protocols: Protocols, 
/**
 * 站点公布的模型表，已按分组过滤。空 = 没公布，或者这个分组没有模型。
 */
models: Array<StationModel>, 
/**
 * 价目那一步的问题，一句话。`None` = 拉到了。
 */
pricing_problem: string | null, 
/**
 * New API 在 `/api/status` 公布的在线充值价（1 美元额度付几元）。
 *
 * ⛔ **只当参考**，界面写在「充值比例」旁边、不自动填 —— 这一格默认 7.3，
 * 很多站没改过、实际靠兑换码按 1 元卖。见 `station_ops::published_topup_price`。
 */
topup_hint: number | null, };
