// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Axis } from "./Axis";
import type { Row } from "./Row";

/**
 * 排序的完整结论。**每一条都要能在界面上说清楚,不许只给一个赢家。**
 */
export type Ranking = { 
/**
 * 按最弱项得分降序;没得分的排在后面。同分按 `route_id` 定序,
 * 保证同样的输入永远给同样的输出 —— 否则迟滞会被随机顺序绕过去。
 */
rows: Array<Row>, winner: string | null, 
/**
 * 这一轮真的换了上游没有。
 */
switched: boolean, 
/**
 * 现任因为迟滞被留下了 —— 挑战者更好,但没好够 [`HYSTERESIS`]。
 */
held_by_hysteresis: boolean, 
/**
 * 这几维全场差距太小,**已如实排除,没有参与排序**。
 */
indistinguishable: Array<Axis>, 
/**
 * 底线把所有还活着的线路都卡掉了,已经放开。**绝不制造死局。**
 */
floors_relaxed: boolean, 
/**
 * 全熔断了,已经放开。同样绝不制造死局 —— 上层照样要如实报错。
 */
breakers_relaxed: boolean, };
