// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 这家站点是按哪套口径公布价格的。
 *
 * **从「谁填了」推出来,不从一个单独的 kind 字段读** —— 字段与内容对不上时
 * (适配器改了、迁移漏了、手改过配置),字段会骗人而内容不会。
 */
export type RateBasis = "per-request" | "ratios" | "absolute-prices" | "unknown";
