// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 本机路由现在什么样。
 */
export type RouterStatus = { running: boolean, 
/**
 * 客户端该把 base_url 指到哪。`None` = 还没启动。
 */
base_url: string | null, 
/**
 * **这个软件**当前的上游线路 id。
 *
 * 三个软件各走各的上游 —— 只给一个的话，界面上「正在路由」那一行
 * 在另外两个分页上会显示成空的，而实际它们各自有线在跑。
 */
current_route: string | null, 
/**
 * 三个软件各自的当前上游（键是 kebab-case 的软件名）。
 */
current_by_client: { [key in string]?: string }, 
/**
 * 这个软件排队等下一发请求生效的那条。
 */
pending_route: string | null, 
/**
 * 换过几次上游。迟滞有没有在起作用,看这个数。
 */
switches: number, 
/**
 * 还没落库的请求日志条数。
 */
pending_logs: number, 
/**
 * 官方 Codex turn-state 上游挂上了没有（Codex 接进路由了没）。
 *
 * **Codex 全局,与界面停在哪个分页无关** —— 官方线整机只有一条。
 * turn-state 面板据此显示「已接入 / 未接入」。
 */
turnstate_official_armed: boolean, 
/**
 * turn-state 注入总开关现在开着没有（**后端真实状态**,界面的开关照它显示）。
 *
 * 只在使用者手动开启后为真;面板重启后回到关（不落盘）—— 这是「默认关闭」
 * 那条硬约束的一部分,不是遗漏。
 */
turnstate_enabled: boolean, 
/**
 * 账号规则是不是 Team（12 块 / 332）;否则个人（10 块 / 292）。
 */
turnstate_team: boolean, 
/**
 * 识别正作用于哪个 Codex 账户槽位（槽位名）。`None` = 识别关着。
 *
 * 0.24.7 起识别**直接作用于激活槽位**（改它的 `config.toml`，不复制凭证、不另起
 * Codex），落盘的 marker 是唯一真相 —— 面板重启后 `turnstate_official_armed` 归零，
 * 而这个字段还能告诉界面「上次没关干净」（启动时会自动关闭并恢复）。
 */
turnstate_takeover: string | null, };
