// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 本机路由现在什么样。
 */
export type RouterStatus = { running: boolean, 
/**
 * 客户端该把 base_url 指到哪。`None` = 还没启动。
 */
base_url: string | null, 
/**
 * **这个软件**当前的上游线路 id。
 *
 * 三个软件各走各的上游 —— 只给一个的话，界面上「正在路由」那一行
 * 在另外两个分页上会显示成空的，而实际它们各自有线在跑。
 */
current_route: string | null, 
/**
 * 三个软件各自的当前上游（键是 kebab-case 的软件名）。
 */
current_by_client: { [key in string]?: string }, 
/**
 * 这个软件排队等下一发请求生效的那条。
 */
pending_route: string | null, 
/**
 * 换过几次上游。迟滞有没有在起作用,看这个数。
 */
switches: number, 
/**
 * 还没落库的请求日志条数。
 */
pending_logs: number, };
