// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一条线路这一轮的健康度摘要。
 */
export type RouteHealthView = { route_id: string, requests: number, 
/**
 * 成功率。**站点没报成败时是 `null`,不是 100%。**
 */
success_rate: number | null, cache_hit_rate: number | null, ttft_p95_ms: number | null, cost_24h: number | null, 
/**
 * 这个窗口里一共用了多少 token（四类之和）。
 *
 * 数在 `health::window::Window` 里一直是现成的，只是没进这个 view ——
 * 界面上「总 Token」那一格因此永远是空的。
 */
tokens_24h: number | null, 
/**
 * 四类 token 各用了多少：输入 / 缓存读 / 缓存写 / 输出。
 *
 * ⛔ **四类要分开给。** 合成一个总数会把「输出翻五倍」这种结构藏掉 ——
 * 而真实用量里输出往往才是花钱的大头。每一类都可能没取证到。
 */
input_tokens: number | null, cache_read_tokens: number | null, cache_write_tokens: number | null, output_tokens: number | null, 
/**
 * 拉取失败的原因。`Some` 时上面那些数是空的,**不是「零请求」**。
 */
error: string | null, };
