// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StationModel } from "./StationModel";

/**
 * 跑一轮检验。
 *
 * ⛔ **会计费。** 只在使用者点的时候调 —— 面板里没有任何自动触发它的路径。
 *
 * 结论会回流:量到 mult 就写回线路的 `latest_mult`,于是排序和底线立刻
 * 按真实倍率走。**但不拉黑** —— 真实倍率仍然过线的照样留在池子里。
 * 一条线路(站点 + 分组)上能用哪些模型。
 *
 * 界面上「站点 → 分组 → 模型」三级里的第三级 —— 前两级就是线路本身。
 *
 * # ⛔ 拉不到不是错
 *
 * 站点没开 `/api/pricing`、Key 过期、网断了,都只是 `models` 为空 +
 * `problem` 写一句话。**界面照样让使用者自己填模型名** ——
 * 报成错的话,这种站一个模型都验不了。
 */
export type StationModelsView = { 
/**
 * 这个分组里能用的模型,按站点公布的顺序。
 */
models: Array<StationModel>, 
/**
 * 建议先验哪个(`claude-opus-5` / `gpt-5.6-sol`,站点有才用)。
 *
 * `None` = 站点一个模型都没公布,界面上要让使用者自己填。
 */
recommended: string | null, 
/**
 * 没拉到的原因。**非空不代表坏了**,只是这一级没法自动列出来。
 */
problem: string | null, };
