// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditRound } from "./AuditRound";

/**
 * 一轮检验连同它属于哪条线路。
 *
 * 表是 `(id, body)` 的,所以线路 id 要跟着 body 走 —— 靠解析主键前缀
 * 去猜属于谁,分组名里有分隔符就会猜错。
 */
export type StoredAudit = { route_id: string, round: AuditRound, };
