// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AntigravityAccounts } from "./AntigravityAccounts";
import type { AntigravityHubIdentity } from "./AntigravityHubIdentity";
import type { AntigravityIdentity } from "./AntigravityIdentity";
import type { ProductStatus } from "./ProductStatus";

export type AntigravityStatus = { hub: ProductStatus, ide: ProductStatus, 
/**
 * 归不归门禁管（设置里存的是反义的 `antigravity_outside_gate`）。
 */
under_gate: boolean, 
/**
 * Hub 的「自动检查更新」。`None` = 读不到（还没起过）。
 */
auto_update: boolean | null, 
/**
 * 语言服务器日志里见没见过「Auth succeeded」。`None` = 没日志。**零凭证信号。**
 */
login_seen: boolean | null, 
/**
 * Hub 登没登录（凭据管理器里那条 `gemini:antigravity` 在不在）。**不读内容。**
 */
hub_logged_in: boolean, 
/**
 * Hub 登的是谁（0.32.0）。
 *
 * **零网络请求** —— 邮箱是从那条凭据里的 `id_token` 载荷本机解出来的，
 * 不是问 Google 要的。Hub 在本机别处一个字的身份都没写，见
 * [`qb_accounts::antigravity::hub`] 的模块头。
 */
hub_identity: AntigravityHubIdentity | null, 
/**
 * 读 Hub 身份时出的错（凭据读不出来 / 形状不认识），界面照实显示。
 *
 * ⛔ **读不出来不是「没登录」**（§7.17）。两者在界面上是两句话。
 */
hub_identity_error: string | null, gemini_cli_installed: boolean, 
/**
 * 反重力账户槽位（0.32.0）：**一个 Google 账户一条，底下两半**
 * （IDE 的 `--user-data-dir` + Gemini CLI 的 `GEMINI_CLI_HOME`）。
 *
 * 取代了 0.30.0 的 `ide_accounts` + `gemini` 两份清单 —— 那两份在界面上是两个页签，
 * 于是同一个账户要建两次、登两次，而只用 IDE 的人永远看着一句
 * 「Gemini CLI · 0 个槽位」。升级迁移见 [`account::migrate`]。
 */
accounts: AntigravityAccounts, 
/**
 * 下面那份账户状态读自哪一份 IDE 资料：`"槽位「工作」"` 或 `"默认资料目录"`。
 */
identity_source: string, 
/**
 * IDE 写在本机的账户状态（邮箱 / 档位 / 各模型剩余额度）。`None` = 那份资料还没登录过。
 */
identity: AntigravityIdentity | null, 
/**
 * 读账户状态时出的错（库正忙 / 损坏），界面照实显示；`None` = 没出错。
 */
identity_error: string | null, };
