// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AntigravityIdeSlot = { id: string, label: string, active: boolean, logged_in: boolean, 
/**
 * 一句人话：已登录 / 未登录 / 状态库不可读。
 */
auth_state: string, 
/**
 * IDE 自己写下的邮箱与档位（`userStatus`），读不到就是 `None`。
 */
email: string | null, tier: string | null, 
/**
 * `--user-data-dir` 指向的目录，给界面显示。
 */
user_data: string, };
