// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 哪一组额度。Google 的分组叫「Claude and GPT models」—— Claude 与 GPT-OSS 共用一份。
 */
export type AntigravityQuotaGroup = "claude" | "gemini";
