// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AntigravityQuotaGroup } from "./AntigravityQuotaGroup";
import type { AntigravityQuotaSpan } from "./AntigravityQuotaSpan";

/**
 * 一格额度。
 */
export type AntigravityQuotaWindow = { group: AntigravityQuotaGroup, span: AntigravityQuotaSpan, 
/**
 * 剩余比例 0–1。
 */
remaining: number, 
/**
 * `true` = Google 没给比例、按 proto3 缺省值算成了 0（见模块头）。界面要说出来。
 */
remaining_implied: boolean, 
/**
 * 重置时刻的 Unix 秒。没用过的窗口 Google 给的是「现在 + 窗口长度」，每问一次都往后挪。
 */
reset_epoch: number | null, 
/**
 * 重置时刻，本地 `YYYY-MM-DD HH:MM`。
 */
reset_at: string | null, 
/**
 * Google 给这一格的说明（部分用掉时才有），原样。
 */
note: string | null, };
