// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 点了之后发生了什么。每一句都是界面原样显示的纯文本。
 */
export type ClaudeZhOutcome = { 
/**
 * 核验全过。
 */
ok: boolean, 
/**
 * 逐条核验结果与做了什么。
 */
lines: Array<string>, 
/**
 * 核验发现越线，已自动还原并停用了那一版上游。
 */
restored: boolean, 
/**
 * 用的是上游哪一版。
 */
tag: string | null, };
