// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 点了之后发生了什么。每一句都是界面原样显示的纯文本。
 */
export type CodexLocaleOutcome = { 
/**
 * 真的改了几个文件。
 */
changed: number, 
/**
 * 逐份说明：改了 / 本来就是 / 跳过（带原因）。
 */
lines: Array<string>, 
/**
 * 重开 GPT 的结果（命令层填）。没关过就是 `None`。
 */
reopened: string | null, };
