// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一份 `CODEX_HOME` 的现状。
 */
export type CodexLocaleHome = { 
/**
 * 界面上显示的名字：槽位名，或者「默认」那一份的说明。
 */
label: string, 
/**
 * 要改的那个 `config.toml` 的完整路径（弹窗里逐个列出来）。
 */
config: string, 
/**
 * 现在 `[desktop] localeOverride` 的值。`None` = 没设，跟随 GPT 自己的默认。
 */
current: string | null, 
/**
 * 读不出来的原因（不是 UTF-8、不是有效 TOML）。有值时这一份不改。
 */
error: string | null, 
/**
 * GPT 上一次用这份资料运行时自己写下的界面语言（`computer-use\config.json` 的 `locale`）。
 *
 * 它说明 GPT **读到了**这项设置，不说明界面真的翻译了 —— 那还要看 `enable_i18n`。
 */
adopted: string | null, 
/**
 * 是不是默认那一份（开始菜单、`codex://` 链接起的 GPT 用它）。
 */
is_default: boolean, };
