// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodexLocaleHome } from "./CodexLocaleHome";

/**
 * 弹窗要的全部事实。
 */
export type CodexLocaleStatus = { 
/**
 * 使用者上次点的是「设为中文」（`settings.gpt_ui_zh`）。新建槽位按它预写。
 */
enabled: boolean, homes: Array<CodexLocaleHome>, 
/**
 * 面板起的 GPT 桌面端开着几个 —— 改之前要先关，改完重开当前槽位。
 */
ours_running: number, 
/**
 * 别处起的开着几个 —— 开着的时候默认那一份不改。
 */
foreign_running: number, 
/**
 * 查不到进程时的原因。**查不到不是「没有」**（§7.17），这时不改。
 */
processes_error: string | null, 
/**
 * Codex 出站插件在跑：它整份接管着槽位的 `config.toml`，这时不改。
 */
egress_running: boolean, };
