// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 美元按四类拆开（缓存写含两档）。
 */
export type CostParts = { input: number, output: number, cache_write: number, cache_read: number, };
