// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckItem } from "./CheckItem";

export type EgressChecks = { items: Array<CheckItem>, 
/**
 * 这一轮跑的时刻，本地 `YYYY-MM-DD HH:MM`。
 */
checked_at: string, undoable: Array<string>, };
