// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GeminiBridgeStatus = { running: boolean, port: number, 
/**
 * 酒馆里 Custom 源要填的地址，带 `/v1`。
 */
url: string, 
/**
 * 在用（或将要用）的 Gemini 槽位标签。没有激活槽位就是 `None`。
 */
slot: string | null, slot_logged_in: boolean, 
/**
 * `node.exe` + 入口脚本。
 */
gemini_cli: string | null, token_path: string, model: string, detail: string, };
