// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeminiSlot } from "./GeminiSlot";

export type GeminiAccounts = { slots: Array<GeminiSlot>, };
