// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 给界面看的状态。`running = false` 时后几项仍然有用（下一次会用哪个槽位、哪份 exe）。
 */
export type GptBridgeStatus = { running: boolean, port: number, 
/**
 * 酒馆里 Custom 源要填的地址，带 `/v1`。
 */
url: string, 
/**
 * 在用（或将要用）的 GPT 槽位标签。没有激活槽位就是 `None`。
 */
slot: string | null, slot_logged_in: boolean, codex_exe: string | null, 
/**
 * Bearer token 存在哪。内容不在这里 —— 要用 `token()` 单独取。
 */
token_path: string, model: string, effort: string, persist_sessions: boolean, 
/**
 * 一句人话：在跑 / 没跑 / 缺什么。
 */
detail: string, };
