// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 「按什么价算」那张小表的一行。
 */
export type PriceUsed = { model: string, input: number, output: number, cache_read: number, cache_write_5m: number, cache_write_1h: number, 
/**
 * 这三项是不是按官方倍数推的（官方表里没单独标）。
 */
cache_read_derived: boolean, cache_write_5m_derived: boolean, cache_write_1h_derived: boolean, 
/**
 * 这次启动抓回来的（`true`）还是内置快照（`false`）。
 */
live: boolean, 
/**
 * 核对 / 抓取那天，`YYYY-MM-DD`。
 */
verified_at: string, };
