// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProbeState } from "./ProbeState";

export type ProbeResult = { state: ProbeState, 
/**
 * 一句人话。**纯文本渲染**，别写 Markdown 的星号。
 */
detail: string, 
/**
 * 本地 `YYYY-MM-DD HH:MM`。
 */
checked_at: string, };
