// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AntigravityProduct } from "./AntigravityProduct";

export type ProductStatus = { product: AntigravityProduct, label: string, installed: boolean, path: string, 
/**
 * 面板托管、正在跑的会话（不含使用者自己从开始菜单起的 —— 那要枚举进程，太重，软件页才做）。
 */
session_id: string | null, pid: number | null, 
/**
 * 语言服务器的数据目录（只显示）。
 */
data_dir: string, };
