// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Profile } from "./Profile";

export type ProfileStore = { profiles: Array<Profile>, 
/**
 * 上一次应用的是哪一个。只是显示用 —— 档案不保证当前状态仍与它一致，
 * 用户完全可能应用完档案又手动改了某一处。
 */
last_applied: string | null, };
