// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一项属于哪一类。界面按这个分组，确认框也按这个分段列。
 */
export type PurgeCategory = "program" | "version_store" | "cache" | "config" | "auth" | "env_path" | "shell_line" | "startup" | "account_slot" | "browser_data";
