// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PurgeAction } from "./PurgeAction";
import type { PurgeCategory } from "./PurgeCategory";
import type { PurgeTarget } from "./PurgeTarget";

/**
 * 盘点出来的一项。
 *
 * ⛔ **结构上装不下密钥、Token、Cookie 的内容。** 加字段之前先读文件头那两条。
 */
export type PurgeItem = { target: PurgeTarget, category: PurgeCategory, action: PurgeAction, 
/**
 * 绝对路径，或者要卸载的包名 / 登记项名 / 变量名。
 */
subject: string, 
/**
 * 归属依据：凭什么认定它属于这个软件。界面上逐条显示。
 */
why: string, };
