// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PurgeItem } from "./PurgeItem";

/**
 * 一次完全卸载的结果。**逐项报，做不到的照实说。**
 */
export type PurgeReport = { done: Array<string>, failed: Array<string>, 
/**
 * 做不到或者故意没做的，照实说。
 */
notes: Array<string>, 
/**
 * 执行完**复扫**一遍还剩下的。空 = 真的清干净了。
 *
 * 这一项是文档阶段 6 要的：不看「命令报了成功」，看重新扫一遍还剩什么。
 */
left: Array<PurgeItem>, };
