// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一个时间窗口花了多少。
 */
export type SpendWindow = { 
/**
 * 认得出价的那部分折算多少美元。窗口里一个价都认不出（或者根本没记录）是 `None`。
 */
usd: number | null, 
/**
 * 窗口里有几条回复。`0` = 没有记录 —— 界面要说「没有记录」，不说「$0」。
 */
messages: number, 
/**
 * 其中几条的模型没有官方价，没算进 `usd`。
 */
unpriced_messages: number, };
