// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StationBillingSettings = { backend: string, user_id: string, configured: boolean, account: string, balance: number | null, currency: string, verified_at: bigint | null, };
