// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TavernRoleplayTest = { provider: string, ok: boolean, model: string | null, reply: string | null, latency_ms: number | null, input_tokens: number | null, output_tokens: number | null, detail: string, tested_at: string, };
