// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TavernGeminiModelQuota = { model_id: string | null, label: string, token_type: string | null, remaining_percent: number | null, reset_at: string | null, reset_epoch: number | null, };
