// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TavernGeminiModelQuota = { model_id: string | null, label: string, token_type: string | null, remaining_percent: number | null, reset_at: string | null, reset_epoch: number | null, 
/**
 * 这一格只有 `resetTime`、没有 `remainingFraction`，按 0 算的（proto3 的 JSON 把零值字段整个省掉）。
 * 界面上要说出来（CLAUDE.md「联网额度」第 6 条，2026-09-25 补上 —— 原来这一格被当成「没读到」，
 * 用光的那一格反而不显示，「剩余配额」取到的是别的、更高的那一格）。
 */
remaining_implied: boolean, };
