// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TavernGeminiModelQuota } from "./TavernGeminiModelQuota";

export type TavernGeminiQuota = { provider: string, account: string | null, project: string | null, tier: string | null, models: Array<TavernGeminiModelQuota>, fetched_at: string, source: string, };
