// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 今天某一个小时的合计。「今天」那一档按小时画柱子用。只列有记录的小时。
 */
export type TokenHour = { 
/**
 * 本地小时，0–23。
 */
hour: number, input: number, output: number, cache_read: number, cache_write: number, cache_write_1h: number, messages: number, cost_usd: number | null, };
