// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TokenSummary = { 
/**
 * 这一档统计的是几天（`1` = 今天，`0` = 全部）。
 */
days: number, input: number, output: number, cache_write: number, cache_read: number, 
/**
 * 回复数。
 */
messages: number, 
/**
 * 缓存命中率 0–1：`缓存读 ÷（输入 + 缓存读 + 缓存写）`。
 *
 * **输出不进分母** —— 输出是生成出来的，从来就没有「命中」一说，
 * 把它算进去只会让这个比例随着回答长短乱飘。
 * 分母为 0 时是 `None`（还没读过任何上文），不是 0。
 */
hit_rate: number | null, 
/**
 * 缓存省下多少（美元）。口径见模块头。算不出来就是 `None`。
 */
saved_usd: number | null, 
/**
 * 有几个模型的官方价没认出来，那部分没算进 `saved_usd`。
 */
unpriced_models: number, 
/**
 * 同一档时间范围里，**归不到任何槽位**的用量（默认目录里没有归属标记的
 * 那部分）。见 `tokens.rs` 文件头：今天这一整天的记录全都没有标记，
 * 所以这个数经常比账户自己的还大。界面必须单独显示，不许并进总数。
 */
unattributed: number, 
/**
 * 上面那部分有几条回复。
 */
unattributed_messages: number, 
/**
 * 用的是编译进去的价格快照（`true`）还是抓回来的官方价（`false`）。
 * 界面要分得出来 —— 快照可能已经过期。
 *
 * 一个价都没取到时是 `None`：那时候「用的是快照还是实时价」根本不成立，
 * 报 `true` 等于说「用了快照」，而实际什么都没用上。
 */
priced_from_snapshot: boolean | null, };
