// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CostParts } from "./CostParts";
import type { Coverage } from "./Coverage";
import type { PriceUsed } from "./PriceUsed";
import type { SpendWindows } from "./SpendWindows";
import type { TokenDay } from "./TokenDay";
import type { TokenHour } from "./TokenHour";
import type { TokenModel } from "./TokenModel";
import type { TokenRequestView } from "./TokenRequestView";
import type { UnpricedModel } from "./UnpricedModel";

export type TokenSummary = { 
/**
 * 这一档统计的是几天（`1` = 今天，`0` = 全部）。
 */
days: number, input: number, output: number, 
/**
 * 缓存写合计（两档）。
 */
cache_write: number, 
/**
 * 其中 1 小时档。
 */
cache_write_1h: number, cache_read: number, 
/**
 * 回复数。四类全 0 的报错不算（见 `empty_replies`）。
 */
messages: number, 
/**
 * 缓存命中率 0–1：`缓存读 ÷（输入 + 缓存读 + 缓存写）`。
 *
 * **输出不进分母** —— 输出是生成出来的，从来就没有「命中」一说，
 * 把它算进去只会让这个比例随着回答长短乱飘。
 * 分母为 0 时是 `None`（还没读过任何上文），不是 0。
 */
hit_rate: number | null, 
/**
 * 缓存省下多少（美元）：缓存读 ×（输入价 − 缓存读价）。算不出来就是 `None`。
 */
saved_usd: number | null, 
/**
 * 有几个模型的官方价没认出来，那部分没算进美元。明细在 `unpriced`。
 */
unpriced_models: number, 
/**
 * 同一档时间范围里，**归不到任何槽位**的用量（默认目录里没有归属标记的
 * 那部分）。界面必须单独显示，不许并进总数。
 */
unattributed: number, 
/**
 * 上面那部分有几条回复。
 */
unattributed_messages: number, 
/**
 * 用的是编译进去的价格快照（`true`）还是抓回来的官方价（`false`）。
 * 界面要分得出来 —— 快照可能已经过期。
 *
 * 一个价都没取到时是 `None`：那时候「用的是快照还是实时价」根本不成立。
 */
priced_from_snapshot: boolean | null, 
/**
 * 按天的合计，旧到新。只列**真有记录的那几天**，见 [`TokenDay`]。
 */
daily: Array<TokenDay>, 
/**
 * 这一档按官方 API 价折算的美元（认得出价的那部分）。一个价都认不出是 `None`。
 */
cost_usd: number | null, 
/**
 * 上面那个数按四类拆开。
 */
cost_parts: CostParts | null, 
/**
 * 今天 / 7 天 / 30 天，不随 `days` 变。
 */
spend: SpendWindows, 
/**
 * 按模型，美元多的在前（没有价的排后面）。
 */
models: Array<TokenModel>, 
/**
 * `days == 1` 且要明细时才有：今天按小时。
 */
hourly: Array<TokenHour>, 
/**
 * 要明细时才有：这一档里最近的回复，新的在前，最多 [`RECENT_VIEW_CAP`] 条。
 */
recent: Array<TokenRequestView>, 
/**
 * 这一档里四类全 0、没入账的回复数（报错、被打断）。
 */
empty_replies: number, 
/**
 * 这一档里最后一条回复的本地时刻，`YYYY-MM-DD HH:MM:SS`。
 */
last_at: string | null, 
/**
 * 认不出价的模型与它们的量。
 */
unpriced: Array<UnpricedModel>, 
/**
 * 这一档里用到的价（要明细时才有）。
 */
prices_used: Array<PriceUsed>, 
/**
 * 覆盖了多少文件。反重力 / GPT 那两条路径给不出来，是 `None`。
 */
coverage: Coverage | null, };
