// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一天的合计。用量明细页的趋势图与按天明细拿它画。
 *
 * ⛔ **没有记录的那一天不出现在这个列表里。** 补一个 0 进来看上去无害，
 * 但那是在断言「这天没用」—— 而真相可能是那天的记录读不出来。
 * 画图那一侧自己决定怎么处理缺口（柱状图不画那一根，提示里写「没有记录」）。
 */
export type TokenDay = { 
/**
 * 本地 `YYYY-MM-DD`。
 */
day: string, input: number, output: number, cache_read: number, 
/**
 * 缓存写合计（两档）。
 */
cache_write: number, 
/**
 * 其中 1 小时档。
 */
cache_write_1h: number, messages: number, 
/**
 * 这一天按官方 API 价折算多少美元（认得出价的那部分）。一个价都认不出是 `None`。
 */
cost_usd: number | null, };
