// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 「最近请求」的一行，带这一条折算的美元。
 */
export type TokenRequestView = { day: string, time: string, model: string, input: number, output: number, cache_write: number, cache_write_1h: number, cache_read: number, project: string, session: string, cost_usd: number | null, };
