// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一个认不出价的模型，以及它在这一档里有多少量。
 */
export type UnpricedModel = { model: string, messages: number, 
/**
 * 四类 token 合计。
 */
tokens: number, };
