// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountSpend } from "./AccountSpend";
import type { TokenSummary } from "./TokenSummary";

/**
 * 用量明细页要的全部：当前槽位的完整小结 + 按账户。
 */
export type UsageOverview = { summary: TokenSummary, by_account: Array<AccountSpend>, };
