// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WatchMode } from "./WatchMode";

export type Lease = { holders: { [key in string]?: WatchMode | null }, holder: string | null, granted: Array<string>, 
/**
 * 这个租约挂的是哪一档看门狗。
 *
 * 面板重启后要按原样把看门狗接回去 —— 接错档比不接更糟：
 * 把桌面端接成 Cli 档，等于把「查不到 IP 立即关闭」偷偷改成 180 秒宽限，
 * 而使用者以为自己还在严格档上。
 */
mode: WatchMode | null, };
