// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditCheck } from "./AuditCheck";
import type { CategoryVerdict } from "./CategoryVerdict";
import type { EvidenceLevel } from "./EvidenceLevel";

/**
 * 一轮检验。
 *
 * **`mult` 记在每一轮上,不是记在线路上** —— 历史里才看得出这家是
 * 越来越离谱还是在收敛。线路上只缓存最近一轮的值,因为排序每次都要用。
 */
export type AuditRound = { at_ms: bigint, checks: Array<AuditCheck>, 
/**
 * 可信度 0–100。
 */
trust: number, 
/**
 * 实扣是标称的几倍。由 [`CheckKind::Rate`] 那一项算出来,
 * 没测到就是 `None`(而不是 1.0 —— 那等于断言「属实」)。
 */
mult: number | null, 
/**
 * 这一轮有多少证据撑着。**界面必须跟可信度一起显示** ——
 * 29 分「证据不足」和 29 分「证据充分」该做的事完全相反。
 */
evidence: EvidenceLevel, 
/**
 * 四类单价各自的对照(输入 / 缓存读 / 缓存写 / 输出)。
 *
 * ⛔ **倍率不是一个数。** 只报一个总倍率,会被「输入便宜、输出贵三倍」
 * 这种结构藏过去 —— 而真实用量里输出往往才是花钱的大头。
 * 报告页那几行画的就是这个。
 */
rates: Array<CategoryVerdict>, 
/**
 * 这一轮验的是哪个模型。空串 = 老数据,不知道。
 *
 * ⛔ **上面那张价目表离开它就没法读。** 「官方单价 $5」是哪个模型的
 * $5?不同模型差十倍,看的人没法自己核对,只能选择信或不信 ——
 * 而「只能选择信」正是这个面板整体想避免的事。
 */
model: string, };
