// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一条线路在某一维上的归一化得分。
 */
export type AxisScore = { "kind": "ratio", "value": number } | { "kind": "missing" };
