// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PriceBasis } from "./PriceBasis";
import type { PriceCategory } from "./PriceCategory";
import type { RateBasis } from "./RateBasis";

/**
 * 四类里的一类:**站点自己公布的计费结构**长什么样。
 *
 * # ⛔ 这个结构体不声称能证明「超没超收」
 *
 * 它曾经有一个 `real_multiplier` 字段,注释写着
 * 「真实倍率 = 站点单价 × 标称倍率 ÷ 官方单价」。那个算式在真实调用路径上
 * **恒等于站点自己公布的两个数相乘** —— 因为当时调用方
 * (`station_ops::run_audit`)手里从来没有站点的绝对单价,它拿站点公布的
 * 倍率乘上官方价凑出一个「站点单价」,`verdicts` 再除回去:
 *
 * ```text
 * 凑出来的单价     = category_ratio × official
 * real_multiplier = 凑出来的单价 × advertised ÷ official
 *                 = category_ratio × advertised        ← official 被约掉了
 * ```
 *
 * 也就是说:站点说它便宜,这张表就说它便宜。「官方单价」那一列与
 * [`PriceBasis`] 在那条路径上是纯装饰,改它们不会让任何判定变化。
 * 这是「看起来通过了、实际什么都没测」的那一类失效 —— 比没有这项检查更危险。
 *
 * # 现在它只报「站点自己说了什么」,换成同一个单位
 *
 * | 站点后端   | 它公布什么                        | `station_price` 怎么来 |
 * |------------|-----------------------------------|------------------------|
 * | New API 系 | 倍率(1 = $2 / 百万 token)         | 倍率 × [`NEW_API_USD_PER_MTOK`] |
 * | sub2api 系 | 绝对单价,美元／百万 token          | 原样 |
 *
 * 两种都乘上站点公布的分组倍率(知道的话)—— 跟它们自己定价页上显示的单价是同一个数。
 * ⛔ **官方价不参与 `station_price`**:New API 那个 2 是它源码里写死的单位,不是
 * 官方价。上面那条失效的根子是「拿官方价凑站点单价」,官方价因此被约掉;这里官方价
 * 只在界面上当分母出现一次,改官方价结论就跟着变。
 *
 * 「它到底收了几倍」由 [`measured_multiplier`] 回答 —— 那一个的分子是
 * 站点账单上真金白银的实扣,分母是同一批 token 按官方单价算出来的成本,
 * 两头都不是站点公布的数。
 */
export type CategoryVerdict = { category: PriceCategory, 
/**
 * New API 的原始倍率乘积(`model_ratio` × 子倍率 × 分组倍率 × 峰时倍率),
 * 只为对照站点后台里填的那几个数。
 *
 * ⛔ **不是相对官方的倍数** —— New API 的倍率 1 = $2 / 百万 token,
 * 要看单价用 `station_price`。公布绝对单价的站点(sub2api 系)这一格是 `None`。
 * 0.25.3 及以前存下来的检验历史里,这一格没乘分组倍率,也没有 `station_price`。
 */
station_ratio: number | null, 
/**
 * 站点这一类的**单价**(美元／百万 token,站内额度,已乘分组与峰时)。
 *
 * sub2api 系原样取它公布的单价;New API 系是倍率 × [`NEW_API_USD_PER_MTOK`]。
 */
station_price: number | null, 
/**
 * 这家站点按哪套口径公布价格。界面据此决定显示哪一列。
 */
basis_kind: RateBasis, 
/**
 * 官方这一类每百万 token 多少钱。**只用于显示「本来多少钱」**,
 * 不参与任何「超没超收」的判定。
 */
official: number | null, 
/**
 * 官方价是抄来的还是推出来的 —— 推出来的那几类,任何基于它的结论都要弱一档。
 */
basis: PriceBasis | null, };
