// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckKind } from "./CheckKind";
import type { Verdict } from "./Verdict";

/**
 * 一项检验的结果。三个数对应报告页那三根条子。
 */
export type Check = { kind: CheckKind, 
/**
 * 标称：站点自己说的。
 */
claimed: number | null, 
/**
 * 上次：上一轮实测到的。首次检验时是 `None` ——
 * **第三根条子不画成 0,写「首次检验」。**
 */
previous: number | null, 
/**
 * 实测：这一轮量出来的。
 */
measured: number | null, verdict: Verdict, };
