// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 检验哪一项。
 *
 * 加一项只要动这个枚举和 [`CheckKind::weight`] —— 其余全是派生的。
 */
export type CheckKind = "rate" | "cache-hit" | "context-window" | "max-output" | "first-token" | "success-rate";
