// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 这一轮的结论有多少证据撑着。
 *
 * ⛔ **必须跟可信度分开。** 可信度 29 分有两种完全不同的来源:
 *
 * - 六项都测到了,其中四项对不上 → **证据充分,这站确实有问题**;
 * - 只测到两项,其余没测到 → **证据不足,还不能下结论**。
 *
 * 只给一个分数的话,这两种在界面上长得一模一样,而使用者该做的事完全相反:
 * 前者该换站,后者该再跑一轮检验。
 */
export type EvidenceLevel = "sufficient" | "partial" | "insufficient" | "conflict";
