// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 站点暴露了哪些协议端点。
 *
 * 这决定一条线路能不能用某个客户端启动:Claude Code 要 Anthropic Messages,
 * Codex 要 OpenAI。**「模型是谁家的」和「用哪个客户端启动」是正交的** ——
 * DeepSeek 有 Anthropic 协议端点,所以 ds 模型可以用 Claude Code 跑。
 *
 * 三个都是 `Option<bool>`:`None` = 还没探过,跟「探过了,没有」是两回事。
 * 混成 `false` 的话,界面会把「还没测」显示成「不支持」,用户会以为这站废了。
 */
export type Protocols = { anthropic: boolean | null, openai_chat: boolean | null, openai_responses: boolean | null, };
