// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 倍率这一格该怎么写。**三态,不是两态。**
 *
 * 「没检验过」必须独立于「检验过属实」—— 前者是还没有断言,后者是
 * 有证据的断言。合并成一个「看起来没问题」,使用者就分不出
 * 「这站我查过」和「这站我还没查」。
 */
export type RateTrust = { "kind": "unverified", nominal: number | null, } | { "kind": "verified", rate: number, } | { "kind": "differs", nominal: number, 
/**
 * 真实倍率 = 标称 × mult。
 */
real: number, mult: number, };
