// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Client } from "./Client";
import type { Protocols } from "./Protocols";
import type { StationRates } from "./StationRates";

/**
 * 一条线路。
 */
export type Route = { 
/**
 * `软件 + 站点 id + 分组名`,见 [`Route::make_id`]。
 */
id: string, 
/**
 * 这条线属于哪个软件。**线路按软件独立,站点不按软件复制。**
 *
 * 同一个站点的同一个分组,在 Claude Code 和 Codex 底下是**两行**:
 * 各自绑各自的 key、各自记各自的健康度。站点(域名)那一层则是共享的 ——
 * 总站只是个容器,按软件复制三份会让「余额」在三张卡上各写一遍,
 * 看起来像三笔钱。
 *
 * ⛔ **这一维不能用 `protocols` 推。** Claude Code 与 Claude 桌面端
 * 走的是同一套 Anthropic 协议,协议上分不开 —— 分得开它们的是
 * 本机路由的路径前缀(`/v1/messages` 对 `/cd/v1/messages`)。
 */
client: Client, station_id: string, 
/**
 * 分组名。**空字符串是合法的** —— 有些站点只有一个默认分组。
 */
group: string, 
/**
 * 这个分组绑的那把 key。一个分组一把,没有第三层。
 */
credential_id: string | null, 
/**
 * 站点自己标的分组倍率。
 */
nominal_rate: number | null, 
/**
 * 最近一轮检验量出来的 `mult`。`None` = 没检验过。
 *
 * **完整的 mult 历史不在这里**,在检验轮次里 —— 这里只缓存最近一轮,
 * 因为排序每次都要用它。
 */
latest_mult: number | null, 
/**
 * 这条线上一次被检验是什么时候。`None` = 从没检验过。
 */
last_audit_ms: bigint | null, 
/**
 * 这条线支持哪些协议。
 *
 * **线路出现在哪个客户端分页,只看这个** —— 跟「模型是谁家的」正交:
 * DeepSeek 有 Anthropic 协议端点,所以 ds 模型可以用 Claude Code 跑。
 * 三个都是 `Option<bool>`:`None` = 还没探过,跟「探过了,没有」是两回事。
 */
protocols: Protocols, 
/**
 * 站点公布的计费倍率(`/api/pricing`),检验时顺手学到的。
 *
 * ⛔ New API 的倍率是**单价**(1 = $2 / 百万 token),不是「官方的几倍」;
 * `completion_ratio` 是输出 ÷ 输入,Claude 官方本来就是 5。见
 * [`StationRates`](super::pricing::StationRates)。
 */
rates: StationRates, 
/**
 * 输出比官方的结构多收几倍(检验时拿官方价算的,见
 * [`StationRates::output_markup`](super::pricing::StationRates::output_markup))。
 *
 * **界面要显示「输出加价」** —— 两家站一个把补全倍率调高、一个照官方填时,
 * 光看分组倍率「×0.15 对 ×0.25」会得出完全相反的结论。
 * `None` = 没算过(0.25.3 及以前的线路、官方价里没有这个模型),**不是「没加价」**。
 *
 * 0.25.3 及以前界面上的「翻倍 ×5」读的是 `completion_ratio > 1`,
 * 照官方价收费的 Claude 线路全都挂着它 —— 那个判断是错的,见 7.91。
 */
output_markup: number | null, 
/**
 * 上面那组价是**哪个模型**的。`None` = 还没检验过,不知道。
 *
 * ⛔ 少了这一段,公布绝对单价的站点(sub2api 系)就没法比价 ——
 * 一个「输入 $2.5/百万」换不成倍率,除非知道官方单价是多少,
 * 而官方单价是按模型查的。倍率那一套(New API 系)不需要它,
 * 所以早先没有也没出症状:那一套本来就只报站点自己的数。
 *
 * **不拿线路上配的模型名顶替。** 那个是发请求用的,可能是别名、
 * 可能是空;这个是「价目表上那一行叫什么」。两者对不上的时候
 * 顶替出来的是另一个模型的官方价,算出的倍率会错得看不出来。
 */
rates_model: string | null, };
