// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Axis } from "./Axis";
import type { AxisScore } from "./AxisScore";
import type { FloorMiss } from "./FloorMiss";

/**
 * 排序结果里的一行。
 */
export type Row = { route_id: string, 
/**
 * 最弱项得分(已乘降权系数)。`None` = 选中的维度里有一项没有证据,
 * 或者没有任何维度可排。
 */
score: number | null, 
/**
 * 每一个**参与排序**的维度上的得分。分不出高下的维度不在这里。
 */
per_axis: Array<[Axis, AxisScore]>, 
/**
 * 决定了它总分的那一维 —— 界面上「它差在哪」就写这个。
 */
weakest: Axis | null, 
/**
 * 选中但这条线没有数据的维度。
 */
missing: Array<Axis>, 
/**
 * 没过的底线。**过不了的线不会被拉黑**,只是不参与竞争。
 */
failed_floors: Array<FloorMiss>, 
/**
 * 能不能参与竞争。
 */
eligible: boolean, 
/**
 * 熔断中。界面写「熔断中」,**不写 0 分**。
 */
tripped: boolean, };
