// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 发给界面的状态。**不含 turn-state 的值本身**,只有外形与计数。
 */
export type Status = { 
/**
 * 现在有没有可用的 active。
 */
usable: boolean, version: bigint, 
/**
 * active 的块数,0 = 没有。
 */
blocks: number, 
/**
 * active 的字符长度,0 = 没有。
 */
length: number, remaining_seconds: bigint, 
/**
 * 备用是否就绪。
 */
ready: boolean, strikes: number, 
/**
 * 观测过多少次（含采集与真实响应）。
 */
observations: bigint, };
