// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 站点怎么计费。
 *
 * ⛔ **不是一个倍率。** New API 的每个模型给的是一组比例,输出那一项还要
 * 再乘一次 `completion_ratio` —— 这就是「计费翻倍」:
 *
 * ```text
 * 输入   = model_ratio
 * 输出   = model_ratio × completion_ratio      ← 常见 3~5 倍
 * 缓存读 = model_ratio × cache_ratio
 * 缓存写 = model_ratio × create_cache_ratio
 * 再乘   × 分组倍率 ×(峰时浮动)
 * ```
 *
 * 只拿 `model_ratio` 当「这站的倍率」去比价,会把输出那几倍整个漏掉 ——
 * 而真实用量里输出往往才是花钱的大头。
 */
export type StationRates = { 
/**
 * 输入倍率(New API 的 `model_ratio`)。
 */
model_ratio: number | null, 
/**
 * 输出相对输入的倍数(`completion_ratio`)。**这是「翻倍」那一项。**
 */
completion_ratio: number | null, 
/**
 * 缓存读相对输入的倍数(`cache_ratio`)。
 */
cache_ratio: number | null, 
/**
 * 缓存写相对输入的倍数(`create_cache_ratio`)。
 */
create_cache_ratio: number | null, 
/**
 * 分组倍率。整条线路再乘一次。
 */
group_ratio: number | null, 
/**
 * 峰时浮动倍率。
 *
 * **取它当上界,不取平均** —— 实测有站点峰时浮动到 1.5 倍。
 * 按平均算会让人在峰时付出比预期多的钱,而账面上「没超」。
 */
peak_rate: number | null, 
/**
 * 按次计费的单价。`Some` 时 token 倍率**整个不适用**。
 */
per_request_price: number | null, 
/**
 * 普通输入每百万 token 多少钱。
 */
input_price: number | null, 
/**
 * 缓存读每百万 token 多少钱。
 */
cache_read_price: number | null, 
/**
 * 缓存写每百万 token 多少钱。
 */
cache_write_price: number | null, 
/**
 * 输出每百万 token 多少钱。
 */
output_price: number | null, };
