// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnStateStatus } from "./TurnStateStatus";

/**
 * 一个 model 的 turn-state 状态,给界面按 model 列出来。
 */
export type TurnStateModelStatus = { model: string, status: TurnStateStatus, };
