// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 三个通道名，一次性导给前端。
 *
 * 做成一个结构体而不是三个独立常量，是因为 ts-rs 导的是**类型**不是值 ——
 * 有了这个结构体，前端那边才拿得到一份带着字面量类型的对象。
 */
export type Channels = { task: "gate://task", workspace_changed: "workspace://changed", navigate: "workspace://navigate", };
